<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="EduShpere.AI.Train\**" />
    <Content Remove="EduShpere.AI.Train\**" />
    <EmbeddedResource Remove="EduShpere.AI.Train\**" />
    <None Remove="EduShpere.AI.Train\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="FluentValidation" Version="12.0.0" />
    <PackageReference Include="Google.OrTools" Version="9.14.6206" />
    <PackageReference Include="Google.OrTools.runtime.win-x64" Version="9.14.6206" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.19" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.19">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>
	<ItemGroup>
		<Content Include="models\model.zip">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<CopyToPublishDirectory>Always</CopyToPublishDirectory>
		</Content>
	</ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Application\EduShpere.Application.csproj" />
    <ProjectReference Include="..\Domain\EduShpere.Domain.csproj" />
	  <ProjectReference Include="..\ESP.AIService\ESP.AIService.csproj" ReferenceOutputAssembly="false" />
	  <ProjectReference Include="..\Infrastructure\EduShpere.Infrastructure.csproj" />
    <ProjectReference Include="..\Shared\EduShpere.Shared.csproj" />
  </ItemGroup>

</Project>
