// <auto-generated />
using System;
using EduShpere.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EduShpere.Infrastructure.Migrations
{
    [DbContext(typeof(EduShpereDbContext))]
    [Migration("20250907051856_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EduShpere.Domain.Models.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClubId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Scope")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Activiti__3214EC073E220058");

                    b.HasIndex("ClubId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.ActivityParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Activity__3214EC0707BE3B6F");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "ActivityId", "UserId" }, "ActivityParticipants_index_10")
                        .IsUnique();

                    b.ToTable("ActivityParticipants");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.ActivityReward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Rank")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("StarPoints")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Activity__3214EC07030871D1");

                    b.HasIndex("ActivityId");

                    b.ToTable("ActivityRewards");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AiFlagsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CommentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("FileType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FileUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Mime")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ModerationStatus")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("PostId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Attachme__3214EC07C75D80D4");

                    b.HasIndex("CommentId");

                    b.HasIndex("PostId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.ClassGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__ClassGro__3214EC07D8340F99");

                    b.ToTable("ClassGroups");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.ClassGroupMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassGroupId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__ClassGro__3214EC079279792A");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "ClassGroupId", "UserId" }, "ClassGroupMembers_index_2")
                        .IsUnique();

                    b.ToTable("ClassGroupMembers");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.Club", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvatarUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("CoverUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Clubs__3214EC07E20E6A9B");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Clubs");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.ClubJoinRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__ClubJoin__3214EC07FD2A1A89");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "ClubId", "UserId" }, "ClubJoinRequests_index_4")
                        .IsUnique();

                    b.ToTable("ClubJoinRequests");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.ClubMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__ClubMemb__3214EC07E85B00FA");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "ClubId", "UserId" }, "ClubMembers_index_3")
                        .IsUnique();

                    b.ToTable("ClubMembers");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.CollectionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CollectionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Collecti__3214EC079AA0869A");

                    b.HasIndex("PostId");

                    b.HasIndex(new[] { "CollectionId", "PostId" }, "CollectionItems_index_9")
                        .IsUnique();

                    b.ToTable("CollectionItems");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("int");

                    b.Property<int?>("PostId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Comments__3214EC075E749776");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.CommentLike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CommentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__CommentL__3214EC077975CA6F");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "CommentId", "UserId" }, "CommentLikes_index_7")
                        .IsUnique();

                    b.ToTable("CommentLikes");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsGroup")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Conversa__3214EC0732D38B6C");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.ConversationMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConversationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastReadAt")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Conversa__3214EC07B903B47E");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "ConversationId", "UserId" }, "ConversationMembers_index_13")
                        .IsUnique();

                    b.ToTable("ConversationMembers");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.FavoriteCollection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Favorite__3214EC07D06C8AE1");

                    b.HasIndex("UserId");

                    b.ToTable("FavoriteCollections");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.Follow", b =>
                {
                    b.Property<int>("FollowingUserId")
                        .HasColumnType("int");

                    b.Property<int>("FollowedUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("FollowingUserId", "FollowedUserId");

                    b.HasIndex("FollowedUserId");

                    b.ToTable("Follows");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.Friend", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("FriendId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Friends__3214EC07E8A63F67");

                    b.HasIndex("FriendId");

                    b.HasIndex("UserId");

                    b.ToTable("Friends");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.FriendRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("FromUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ToUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__FriendRe__3214EC07C6DD5A4D");

                    b.HasIndex("ToUserId");

                    b.HasIndex(new[] { "FromUserId", "ToUserId" }, "UX_FriendRequests_Pair")
                        .IsUnique();

                    b.ToTable("FriendRequests");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.PointTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Change")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Reason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("SourceId")
                        .HasColumnType("int");

                    b.Property<int>("SourceType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__PointTra__3214EC075A86985D");

                    b.HasIndex(new[] { "UserId", "CreatedAt" }, "PointTransactions_index_12");

                    b.ToTable("PointTransactions");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ClassGroupId")
                        .HasColumnType("int");

                    b.Property<int?>("ClubId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PrivacyLevel")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Type")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Posts__3214EC07EE391665");

                    b.HasIndex("ClassGroupId");

                    b.HasIndex("ClubId");

                    b.HasIndex(new[] { "UserId", "CreatedAt" }, "IX_Posts_User_CreatedAt");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.PostInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("InterestStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__PostInte__3214EC0728500A76");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "PostId", "UserId" }, "PostInterests_index_8")
                        .IsUnique();

                    b.ToTable("PostInterests");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.PostLike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__PostLike__3214EC0747CA159F");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "PostId", "UserId" }, "PostLikes_index_6")
                        .IsUnique();

                    b.ToTable("PostLikes");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.PostReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("Reason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ReporterId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__PostRepo__3214EC07BC04AE86");

                    b.HasIndex("PostId");

                    b.HasIndex("ReporterId");

                    b.ToTable("PostReports");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.Reward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PointsCost")
                        .HasColumnType("int");

                    b.Property<int>("RewardType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Rewards__3214EC07A02DC01E");

                    b.ToTable("Rewards");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.RewardRedemptionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PointsSpent")
                        .HasColumnType("int");

                    b.Property<int>("RewardId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__RewardRe__3214EC0726FAC239");

                    b.HasIndex("RewardId");

                    b.HasIndex("UserId");

                    b.ToTable("RewardRedemptionLogs");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.School", b =>
                {
                    b.Property<long>("SchoolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SchoolId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("SchoolId")
                        .HasName("PK__Schools__3DA4675B2FE61093");

                    b.ToTable("Schools");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.StudentProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<short?>("EnrollmentYear")
                        .HasColumnType("smallint");

                    b.Property<int>("ExtraJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("StudentNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__StudentP__3214EC077AC05576");

                    b.HasIndex(new[] { "UserId" }, "UQ__StudentP__1788CC4D37CE064E")
                        .IsUnique();

                    b.ToTable("StudentProfiles");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.Submission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("FileUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal?>("Score")
                        .HasColumnType("decimal(9, 2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Submissi__3214EC07D1DBDF8C");

                    b.HasIndex("ActivityId");

                    b.HasIndex("UserId");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.SubmissionVote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SubmissionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Submissi__3214EC070C68EA79");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "SubmissionId", "UserId" }, "SubmissionVotes_index_11")
                        .IsUnique();

                    b.ToTable("SubmissionVotes");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.TeacherProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("ExtraJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SubjectSpecialties")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__TeacherP__3214EC073F32419D");

                    b.HasIndex(new[] { "UserId" }, "UQ__TeacherP__1788CC4D4A59778B")
                        .IsUnique();

                    b.ToTable("TeacherProfiles");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("AvatarUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime?>("CreatedAtLegacy")
                        .HasColumnType("datetime");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<int>("Firstname")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Lastname")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte?>("Role")
                        .HasColumnType("tinyint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long?>("SchoolId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("Username")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC07A3A6D7CF");

                    b.HasIndex("SchoolId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.UserBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BlockedId")
                        .HasColumnType("int");

                    b.Property<int>("BlockerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__UserBloc__3214EC07D9DB2867");

                    b.HasIndex("BlockedId");

                    b.HasIndex(new[] { "BlockerId", "BlockedId" }, "UX_UserBlocks_Pair")
                        .IsUnique();

                    b.ToTable("UserBlocks");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.UserPoint", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Balance")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("UserId")
                        .HasName("PK__UserPoin__1788CC4C981D0001");

                    b.ToTable("UserPoints");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.Activity", b =>
                {
                    b.HasOne("EduShpere.Domain.Models.Club", "Club")
                        .WithMany("Activities")
                        .HasForeignKey("ClubId")
                        .HasConstraintName("FK__Activitie__ClubI__6BE40491");

                    b.HasOne("EduShpere.Domain.Models.User", "CreatedByUser")
                        .WithMany("Activities")
                        .HasForeignKey("CreatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK__Activitie__Creat__6AEFE058");

                    b.Navigation("Club");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.ActivityParticipant", b =>
                {
                    b.HasOne("EduShpere.Domain.Models.Activity", "Activity")
                        .WithMany("ActivityParticipants")
                        .HasForeignKey("ActivityId")
                        .IsRequired()
                        .HasConstraintName("FK__ActivityP__Activ__6DCC4D03");

                    b.HasOne("EduShpere.Domain.Models.User", "User")
                        .WithMany("ActivityParticipants")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__ActivityP__UserI__6EC0713C");

                    b.Navigation("Activity");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.ActivityReward", b =>
                {
                    b.HasOne("EduShpere.Domain.Models.Activity", "Activity")
                        .WithMany("ActivityRewards")
                        .HasForeignKey("ActivityId")
                        .IsRequired()
                        .HasConstraintName("FK__ActivityR__Activ__6CD828CA");

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.Attachment", b =>
                {
                    b.HasOne("EduShpere.Domain.Models.Comment", "Comment")
                        .WithMany("Attachments")
                        .HasForeignKey("CommentId")
                        .HasConstraintName("FK__Attachmen__Comme__5E8A0973");

                    b.HasOne("EduShpere.Domain.Models.Post", "Post")
                        .WithMany("Attachments")
                        .HasForeignKey("PostId")
                        .HasConstraintName("FK__Attachmen__PostI__5D95E53A");

                    b.Navigation("Comment");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.ClassGroupMember", b =>
                {
                    b.HasOne("EduShpere.Domain.Models.ClassGroup", "ClassGroup")
                        .WithMany("ClassGroupMembers")
                        .HasForeignKey("ClassGroupId")
                        .IsRequired()
                        .HasConstraintName("FK__ClassGrou__Class__540C7B00");

                    b.HasOne("EduShpere.Domain.Models.User", "User")
                        .WithMany("ClassGroupMembers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__ClassGrou__UserI__55009F39");

                    b.Navigation("ClassGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.Club", b =>
                {
                    b.HasOne("EduShpere.Domain.Models.User", "CreatedByUser")
                        .WithMany("Clubs")
                        .HasForeignKey("CreatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK__Clubs__CreatedBy__55F4C372");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.ClubJoinRequest", b =>
                {
                    b.HasOne("EduShpere.Domain.Models.Club", "Club")
                        .WithMany("ClubJoinRequests")
                        .HasForeignKey("ClubId")
                        .IsRequired()
                        .HasConstraintName("FK__ClubJoinR__ClubI__58D1301D");

                    b.HasOne("EduShpere.Domain.Models.User", "User")
                        .WithMany("ClubJoinRequests")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__ClubJoinR__UserI__59C55456");

                    b.Navigation("Club");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.ClubMember", b =>
                {
                    b.HasOne("EduShpere.Domain.Models.Club", "Club")
                        .WithMany("ClubMembers")
                        .HasForeignKey("ClubId")
                        .IsRequired()
                        .HasConstraintName("FK__ClubMembe__ClubI__56E8E7AB");

                    b.HasOne("EduShpere.Domain.Models.User", "User")
                        .WithMany("ClubMembers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__ClubMembe__UserI__57DD0BE4");

                    b.Navigation("Club");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.CollectionItem", b =>
                {
                    b.HasOne("EduShpere.Domain.Models.FavoriteCollection", "Collection")
                        .WithMany("CollectionItems")
                        .HasForeignKey("CollectionId")
                        .IsRequired()
                        .HasConstraintName("FK__Collectio__Colle__690797E6");

                    b.HasOne("EduShpere.Domain.Models.Post", "Post")
                        .WithMany("CollectionItems")
                        .HasForeignKey("PostId")
                        .IsRequired()
                        .HasConstraintName("FK__Collectio__PostI__69FBBC1F");

                    b.Navigation("Collection");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.Comment", b =>
                {
                    b.HasOne("EduShpere.Domain.Models.Comment", "ParentComment")
                        .WithMany("InverseParentComment")
                        .HasForeignKey("ParentCommentId")
                        .HasConstraintName("FK__Comments__Parent__625A9A57");

                    b.HasOne("EduShpere.Domain.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .HasConstraintName("FK__Comments__PostId__6166761E");

                    b.HasOne("EduShpere.Domain.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Comments__UserId__634EBE90");

                    b.Navigation("ParentComment");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.CommentLike", b =>
                {
                    b.HasOne("EduShpere.Domain.Models.Comment", "Comment")
                        .WithMany("CommentLikes")
                        .HasForeignKey("CommentId")
                        .IsRequired()
                        .HasConstraintName("FK__CommentLi__Comme__6442E2C9");

                    b.HasOne("EduShpere.Domain.Models.User", "User")
                        .WithMany("CommentLikes")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__CommentLi__UserI__65370702");

                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.ConversationMember", b =>
                {
                    b.HasOne("EduShpere.Domain.Models.Conversation", "Conversation")
                        .WithMany("ConversationMembers")
                        .HasForeignKey("ConversationId")
                        .IsRequired()
                        .HasConstraintName("FK__Conversat__Conve__7755B73D");

                    b.HasOne("EduShpere.Domain.Models.User", "User")
                        .WithMany("ConversationMembers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Conversat__UserI__7849DB76");

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.FavoriteCollection", b =>
                {
                    b.HasOne("EduShpere.Domain.Models.User", "User")
                        .WithMany("FavoriteCollections")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__FavoriteC__UserI__681373AD");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.Follow", b =>
                {
                    b.HasOne("EduShpere.Domain.Models.User", "FollowedUser")
                        .WithMany("FollowFollowedUsers")
                        .HasForeignKey("FollowedUserId")
                        .IsRequired()
                        .HasConstraintName("FK__Follows__Followe__4D5F7D71");

                    b.HasOne("EduShpere.Domain.Models.User", "FollowingUser")
                        .WithMany("FollowFollowingUsers")
                        .HasForeignKey("FollowingUserId")
                        .IsRequired()
                        .HasConstraintName("FK__Follows__Followi__4C6B5938");

                    b.Navigation("FollowedUser");

                    b.Navigation("FollowingUser");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.Friend", b =>
                {
                    b.HasOne("EduShpere.Domain.Models.User", "FriendNavigation")
                        .WithMany("FriendFriendNavigations")
                        .HasForeignKey("FriendId")
                        .IsRequired()
                        .HasConstraintName("FK__Friends__FriendI__531856C7");

                    b.HasOne("EduShpere.Domain.Models.User", "User")
                        .WithMany("FriendUsers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Friends__UserId__5224328E");

                    b.Navigation("FriendNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.FriendRequest", b =>
                {
                    b.HasOne("EduShpere.Domain.Models.User", "FromUser")
                        .WithMany("FriendRequestFromUsers")
                        .HasForeignKey("FromUserId")
                        .IsRequired()
                        .HasConstraintName("FK__FriendReq__FromU__4E53A1AA");

                    b.HasOne("EduShpere.Domain.Models.User", "ToUser")
                        .WithMany("FriendRequestToUsers")
                        .HasForeignKey("ToUserId")
                        .IsRequired()
                        .HasConstraintName("FK__FriendReq__ToUse__4F47C5E3");

                    b.Navigation("FromUser");

                    b.Navigation("ToUser");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.PointTransaction", b =>
                {
                    b.HasOne("EduShpere.Domain.Models.User", "User")
                        .WithMany("PointTransactions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__PointTran__UserI__74794A92");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.Post", b =>
                {
                    b.HasOne("EduShpere.Domain.Models.ClassGroup", "ClassGroup")
                        .WithMany("Posts")
                        .HasForeignKey("ClassGroupId")
                        .HasConstraintName("FK__Posts__ClassGrou__5BAD9CC8");

                    b.HasOne("EduShpere.Domain.Models.Club", "Club")
                        .WithMany("Posts")
                        .HasForeignKey("ClubId")
                        .HasConstraintName("FK__Posts__ClubId__5CA1C101");

                    b.HasOne("EduShpere.Domain.Models.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Posts__UserId__5AB9788F");

                    b.Navigation("ClassGroup");

                    b.Navigation("Club");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.PostInterest", b =>
                {
                    b.HasOne("EduShpere.Domain.Models.Post", "Post")
                        .WithMany("PostInterests")
                        .HasForeignKey("PostId")
                        .IsRequired()
                        .HasConstraintName("FK__PostInter__PostI__662B2B3B");

                    b.HasOne("EduShpere.Domain.Models.User", "User")
                        .WithMany("PostInterests")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__PostInter__UserI__671F4F74");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.PostLike", b =>
                {
                    b.HasOne("EduShpere.Domain.Models.Post", "Post")
                        .WithMany("PostLikes")
                        .HasForeignKey("PostId")
                        .IsRequired()
                        .HasConstraintName("FK__PostLikes__PostI__5F7E2DAC");

                    b.HasOne("EduShpere.Domain.Models.User", "User")
                        .WithMany("PostLikes")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__PostLikes__UserI__607251E5");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.PostReport", b =>
                {
                    b.HasOne("EduShpere.Domain.Models.Post", "Post")
                        .WithMany("PostReports")
                        .HasForeignKey("PostId")
                        .IsRequired()
                        .HasConstraintName("FK__PostRepor__PostI__793DFFAF");

                    b.HasOne("EduShpere.Domain.Models.User", "Reporter")
                        .WithMany("PostReports")
                        .HasForeignKey("ReporterId")
                        .IsRequired()
                        .HasConstraintName("FK__PostRepor__Repor__7A3223E8");

                    b.Navigation("Post");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.RewardRedemptionLog", b =>
                {
                    b.HasOne("EduShpere.Domain.Models.Reward", "Reward")
                        .WithMany("RewardRedemptionLogs")
                        .HasForeignKey("RewardId")
                        .IsRequired()
                        .HasConstraintName("FK__RewardRed__Rewar__76619304");

                    b.HasOne("EduShpere.Domain.Models.User", "User")
                        .WithMany("RewardRedemptionLogs")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__RewardRed__UserI__756D6ECB");

                    b.Navigation("Reward");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.StudentProfile", b =>
                {
                    b.HasOne("EduShpere.Domain.Models.User", "User")
                        .WithOne("StudentProfile")
                        .HasForeignKey("EduShpere.Domain.Models.StudentProfile", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK__StudentPr__UserI__4A8310C6");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.Submission", b =>
                {
                    b.HasOne("EduShpere.Domain.Models.Activity", "Activity")
                        .WithMany("Submissions")
                        .HasForeignKey("ActivityId")
                        .IsRequired()
                        .HasConstraintName("FK__Submissio__Activ__6FB49575");

                    b.HasOne("EduShpere.Domain.Models.User", "User")
                        .WithMany("Submissions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Submissio__UserI__70A8B9AE");

                    b.Navigation("Activity");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.SubmissionVote", b =>
                {
                    b.HasOne("EduShpere.Domain.Models.Submission", "Submission")
                        .WithMany("SubmissionVotes")
                        .HasForeignKey("SubmissionId")
                        .IsRequired()
                        .HasConstraintName("FK__Submissio__Submi__719CDDE7");

                    b.HasOne("EduShpere.Domain.Models.User", "User")
                        .WithMany("SubmissionVotes")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Submissio__UserI__72910220");

                    b.Navigation("Submission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.TeacherProfile", b =>
                {
                    b.HasOne("EduShpere.Domain.Models.User", "User")
                        .WithOne("TeacherProfile")
                        .HasForeignKey("EduShpere.Domain.Models.TeacherProfile", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK__TeacherPr__UserI__4B7734FF");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.User", b =>
                {
                    b.HasOne("EduShpere.Domain.Models.School", "School")
                        .WithMany("Users")
                        .HasForeignKey("SchoolId")
                        .HasConstraintName("FK__Users__SchoolId__498EEC8D");

                    b.Navigation("School");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.UserBlock", b =>
                {
                    b.HasOne("EduShpere.Domain.Models.User", "Blocked")
                        .WithMany("UserBlockBlockeds")
                        .HasForeignKey("BlockedId")
                        .IsRequired()
                        .HasConstraintName("FK__UserBlock__Block__51300E55");

                    b.HasOne("EduShpere.Domain.Models.User", "Blocker")
                        .WithMany("UserBlockBlockers")
                        .HasForeignKey("BlockerId")
                        .IsRequired()
                        .HasConstraintName("FK__UserBlock__Block__503BEA1C");

                    b.Navigation("Blocked");

                    b.Navigation("Blocker");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.UserPoint", b =>
                {
                    b.HasOne("EduShpere.Domain.Models.User", "User")
                        .WithOne("UserPoint")
                        .HasForeignKey("EduShpere.Domain.Models.UserPoint", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK__UserPoint__UserI__73852659");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.Activity", b =>
                {
                    b.Navigation("ActivityParticipants");

                    b.Navigation("ActivityRewards");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.ClassGroup", b =>
                {
                    b.Navigation("ClassGroupMembers");

                    b.Navigation("Posts");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.Club", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("ClubJoinRequests");

                    b.Navigation("ClubMembers");

                    b.Navigation("Posts");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.Comment", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("CommentLikes");

                    b.Navigation("InverseParentComment");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.Conversation", b =>
                {
                    b.Navigation("ConversationMembers");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.FavoriteCollection", b =>
                {
                    b.Navigation("CollectionItems");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.Post", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("CollectionItems");

                    b.Navigation("Comments");

                    b.Navigation("PostInterests");

                    b.Navigation("PostLikes");

                    b.Navigation("PostReports");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.Reward", b =>
                {
                    b.Navigation("RewardRedemptionLogs");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.School", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.Submission", b =>
                {
                    b.Navigation("SubmissionVotes");
                });

            modelBuilder.Entity("EduShpere.Domain.Models.User", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("ActivityParticipants");

                    b.Navigation("ClassGroupMembers");

                    b.Navigation("ClubJoinRequests");

                    b.Navigation("ClubMembers");

                    b.Navigation("Clubs");

                    b.Navigation("CommentLikes");

                    b.Navigation("Comments");

                    b.Navigation("ConversationMembers");

                    b.Navigation("FavoriteCollections");

                    b.Navigation("FollowFollowedUsers");

                    b.Navigation("FollowFollowingUsers");

                    b.Navigation("FriendFriendNavigations");

                    b.Navigation("FriendRequestFromUsers");

                    b.Navigation("FriendRequestToUsers");

                    b.Navigation("FriendUsers");

                    b.Navigation("PointTransactions");

                    b.Navigation("PostInterests");

                    b.Navigation("PostLikes");

                    b.Navigation("PostReports");

                    b.Navigation("Posts");

                    b.Navigation("RewardRedemptionLogs");

                    b.Navigation("StudentProfile");

                    b.Navigation("SubmissionVotes");

                    b.Navigation("Submissions");

                    b.Navigation("TeacherProfile");

                    b.Navigation("UserBlockBlockeds");

                    b.Navigation("UserBlockBlockers");

                    b.Navigation("UserPoint");
                });
#pragma warning restore 612, 618
        }
    }
}
